### ISSUE TITLE
LatexNodes2Text - KeyError: '2'

### ISSUE THREAD

**Issue by JeremyBrent** [phfaist/pylatexenc#110]
I'm relatively new to Latex here, so please be patient with me :) 

I am attempting to convert latex in this abstract:

```python
from pylatexenc.latex2text import LatexNodes2Text
abstract='In \\cite{AP2} we obtained general estimates of the operator moduli of continuity of functions on the real line. In this paper we improve the estimates obtained in \\cite{AP2} for certain special classes of functions. \r\nIn particular, we improve estimates of Kato \\cite{Ka} and show that $$ \\big\\|\\,|S|-|T|\\,\\big\\|\\le C\\|S-T\\|\\log(2+\\log\\frac{\\|S\\|+\\|T\\|}{\\|S-T\\|}) $$ for every bounded operators $S$ and $T$ on Hilbert space. Here $|S|\\df(S^*S)^{1/2}$. Moreover, we show that this inequality is sharp. \r\nWe prove in this paper that if $f$ is a nondecreasing continuous function on $\\R$ that vanishes on $(-\\be,0]$ and is concave on $[0,\\be)$, then its operator modulus of continuity $\\O_f$ admits the estimate $$ \\O_f(\\d)\\le\\const\\int_e^\\be\\frac{f(\\d t)\\,dt}{t^2\\log t},\\quad\\d>0. $$ \r\nWe also study the problem of sharpness of estimates obtained in \\cite{AP2} and \\cite{AP4}. We construct a $C^\\be$ function $f$ on $\\R$ such that $\\|f\\|_{L^\\be}\\le1$, $\\|f\\|_{\\Li}\\le1$, and $$ \\O_f(\\d)\\ge\\const\\,\\d\\sqrt{\\log\\frac2\\d},\\quad\\d\\in(0,1]. $$ \r\nIn the last section of the paper we obtain sharp estimates of $\\|f(A)-f(B)\\|$ in the case when the spectrum of $A$ has $n$ points. Moreover, we obtain a more general result in terms of the $\\e$-entropy of the spectrum that also improves the estimate of the operator moduli of continuity of Lipschitz functions on finite intervals, which was obtained in \\cite{AP2}.'
clean_string = LatexNodes2Text().latex_to_text(abstract)
```
We are getting an Error KeyError: '2'. The full stack trace can be found here: 
```
Traceback (most recent call last):
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-28e7ef817e7b>", line 3, in <module>
    clean_string(inverted_to_text(abs))
  File "/home/jb/diml_sm_utilities/modules/text_utils.py", line 84, in clean_string
    latex_removed = LatexNodes2Text().latex_to_text(
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1021, in latex_to_text
    return self.nodelist_to_text(
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1060, in nodelist_to_text
    s += self.node_to_text(node, textcol=textcol)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1099, in node_to_text
    return self.math_node_to_text(node)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1276, in math_node_to_text
    content = self.nodelist_to_text(node.nodelist).strip()
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1060, in nodelist_to_text
    s += self.node_to_text(node, textcol=textcol)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1090, in node_to_text
    return self.macro_node_to_text(node)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1189, in macro_node_to_text
    macrostr = get_macro_str_repl(node, macroname, mac)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1180, in get_macro_str_repl
    return self.apply_simplify_repl(node, mac.simplify_repl,
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1349, in apply_simplify_repl
    r = simplify_repl(node, **kwargs)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/_defaultspecs.py", line 1571, in <lambda>
    MacroTextSpec(mname, lambda x, l2tobj, c=mcombining: make_accented_char(x, c, l2tobj))
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/_defaultspecs.py", line 1551, in make_accented_char
    c = l2tobj.nodelist_to_text([nodearg]).strip()
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1060, in nodelist_to_text
    s += self.node_to_text(node, textcol=textcol)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1090, in node_to_text
    return self.macro_node_to_text(node)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1189, in macro_node_to_text
    macrostr = get_macro_str_repl(node, macroname, mac)
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1180, in get_macro_str_repl
    return self.apply_simplify_repl(node, mac.simplify_repl,
  File "/home/jb/data_ingestion/venv/lib/python3.10/site-packages/pylatexenc/latex2text/__init__.py", line 1387, in apply_simplify_repl
    return simplify_repl % x
KeyError: '2'
```

We are using 
```
pylatexenc==2.10
Python==3.10.12
```

I haven't found any information about this on Google.

Thanks in advance!

**Comment by phfaist** [comment]
Good catch, thanks. It's fixed in the latest development git version of `pylatexenc` and will be included in the next prerelease.
