### ISSUE TITLE
Incorrect (?) parsing of content in `lstlisting` environment

### ISSUE THREAD

**Issue by sw-dbrown** [phfaist/pylatexenc#90]
Hello, I have though a little bit more about the issue I described in https://github.com/phfaist/pylatexenc/issues/89. While I definitely understand and respect your reasoning I have come to the conclusion that the issue is not related to `nodelist_to_latex()` at all. 

Consider the following example:

```
#!/usr/bin/env python3

from pylatexenc.latexwalker import LatexWalker

w = LatexWalker(
    r"""
\begin{lstlisting}
$ some content that should not be interpreted as tex!
\end{lstlisting}
""",
    tolerant_parsing=False,
)
(nodelist, pos, len_) = w.get_latex_nodes(pos=0)

print(nodelist)
```

It is important to note the presence of `tolerant_parsing=False`. Executing this code leads to the following error message:

```
Traceback (most recent call last):
  File "/tmp/mwe/./mwe.py", line 13, in <module>
    (nodelist, pos, len_) = w.get_latex_nodes(pos=0)
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2376, in get_latex_nodes
    r_endnow = do_read(nodelist, p)
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2245, in do_read
    (envnode, epos, elen) = self.get_latex_environment(
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 1834, in get_latex_environment
    (nodelist, npos, nlen) = self.get_latex_nodes(pos,
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2376, in get_latex_nodes
    r_endnow = do_read(nodelist, p)
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2187, in do_read
    (mathinline_nodelist, mpos, mlen) = self.get_latex_nodes(
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2376, in get_latex_nodes
    r_endnow = do_read(nodelist, p)
  File "/tmp/mwe/venv/lib/python3.10/site-packages/pylatexenc/latexwalker/__init__.py", line 2121, in do_read
    raise LatexWalkerParseError(
pylatexenc.latexwalker.LatexWalkerParseError: Unexpected closing environment: 'lstlisting' @(4,0)
Open LaTeX blocks:
            @(2,0)  begin environment "lstlisting"
            @(3,0)  math mode "$"
```

If `tolerant_parsing` is set to `True`, the script will successfully complete execution and return the following output:

```
[LatexCharsNode(parsing_state=<parsing state 140426563620000>, pos=0, len=1, chars='\n'), 
LatexEnvironmentNode(parsing_state=<parsing state 140426563620000>, pos=1, len=90, environmentname='lstlisting', nodelist=
[LatexCharsNode(parsing_state=<parsing state 140426563620000>, pos=19, len=1, chars='\n'), LatexMathNode(parsing_state=
<parsing state 140426563620000>, pos=20, len=71, displaytype='inline', nodelist=[LatexCharsNode(parsing_state=<parsing state 
140426563621104>, pos=21, len=53, chars=' some content that should not be interpreted as tex!\n'), 
LatexCharsNode(parsing_state=<parsing state 140426563621104>, pos=90, len=1, chars='\n')], delimiters=('$', '$'))], 
nodeargd=ParsedMacroArgs(argspec='', argnlist=[]))]
```

Here, it can be seen that a `LatexMathNode` is created inside of the `lstlisting` environment. In my opinion, this is not correct behavior since content inside of the `lstlisting` environment should be treated as verbatim (one big `LatexCharsNode` (?)). The construction of the unbalanced `LatexMathNode` is what eventually causes `nodelist_to_latex()` to produce invalid latex code but it is, in my opinion, not the root of the problem. Similarly, in the second example in https://github.com/phfaist/pylatexenc/issues/89 the sequence `\"` gets turned into a `LatexMacroNode`.

Substituting the `lstlisting` environment for a verbatim environment instead leads to correct results. 

Again, thank you very much for your time!

**Comment by sw-dbrown** [comment]
Digging a little bit into the source it appears that there is currently no special handling for the `lstlisting` environment as there is for `verbatim`. Should `VerbatimArgsParser` be adapted to handle more environments in addition to `verbatim`?

**Comment by phfaist** [comment]
Thanks for the careful analysis! I'll have a closer look at some point soon.

**Comment by phfaist** [comment]
Closing, because it looks like the desired feature is in the beta version.
